### ISSUE TITLE
Is there a ROS node?

### ISSUE THREAD

**Issue by mzahana** [berktepebag/BOSCH-BMI160-ROS-Library#1]
Thanks @berktepebag  for this package.

It seems that this package is missing a ROS node. Do you have a ROS node that uses this package?

Thank you.

**Comment by berktepebag** [comment]
You are welcome @mzahana. I have to check which ROS node is missing, as there shouldn't be any dependency. I will try to have a look at it as soon as possible.

**Comment by mzahana** [comment]
What I meant is that, if this package is supposed to be a ROS driver for BMI160, then I could not find the ROS node that publishes IMU topic.

Thanks.

**Comment by berktepebag** [comment]
Yes you are right, I checked and I did not add any publisher or anything. I was directly using it in a Kalman Filter in an other ROS node rather than using it "as a ROS node". Maybe naming is confusing, or I should be adding a ROS Node version of it. It's been 4 years since I haven't touched this code, so any help would be appreciated :+1:

**Comment by mzahana** [comment]
@berktepebag I will try to write a ROS publisher node and make a PR. I might need some help to proceed.

I have the following questions to help me in the implementation, if you don't mind.

1. How can I select the ACCEL and GYRO ranges? For exmaple using 4G for acceleration, and 2000deg/s for the gyro?
2. Is it possible to publish ACCEL/GYRO at high rates e.g. 200 Hz? This is needed in some applications such as visual inertial SLAM. For that, do I need to set any sensor parameters ?

Thanks

**Comment by mzahana** [comment]
@berktepebag Also what is the unit of the accelerometers? Is it in g or m/s^2? 
So, if the the sensor is aligned with gravity, would the z-axis read ~ 9.8 m/s^2 and other axes ~ 0.0 m/s^2?

**Comment by berktepebag** [comment]
In bmi160_acc_example:

As you can see there are 2 functions to convert them from raw -> mili G (line 72) -> m/s^2 (line 78). So, unless you change lines 204-206 you will get m/s^2. But you can play with it as you wish, you can also change the resolution and limits (-2G,2G etc. (lines 17-18)). 

You can find different Accel and Gyro ranges in the [datasheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/product_flyer/bst-bmi160-fl000.pdf). I cannot test it right now but changing line 17 "BMI160_ACCEL_RANGE_2G" to "4G", "8G", "16G" should give you better resolution but this should slow down the publish rate (yet you should try it, I have never tried different resolutions as 2G was sufficient).

So, increasing publish rates should be possible (as mentioned above) with lesser resolution but I am not exactly sure how fast it can go. If remember right I was getting 20 and it was more than enough for my case. You can try to increase publisher rate and check how many of them are repeating values.

In lines 179-181, calibration values are subtracted from raw values. Means that, what you will get as a result is "almost" 0 in x,y,z directions while not moving. "Almost" because, vehicles' kinematics will not be always the same as the calibration kinematics.

**Comment by mzahana** [comment]
Thanks @berktepebag for the information.

To check that I get repeating sensor values, is there a timestamp that can be read from the sensor's registers? so I know that two measurements are the same if they have the same timestamp.

Thank you.

**Comment by mzahana** [comment]
I wrote a ROS 1 package based on the implementation in this repo. The package can be found here [bmi160_ros](https://github.com/mzahana/bmi160_ros). It also includes a calibration node. I  hope this helps.
